


/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

import static java.awt.SystemColor.menu;
import javax.swing.JFrame;

public class MenuUtama extends javax.swing.JFrame {

    String ID = UserID.getUserLogin();
    /**
     * Creates new form MenuUtama
     */
    public MenuUtama() {
        initComponents();
        //Lb_Username.setText(ID);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        MenuKaryawan = new javax.swing.JMenuItem();
        MenuBidang = new javax.swing.JMenuItem();
        BtnMenuSuratMasuk = new javax.swing.JMenu();
        BtnMenuSuratKeluar = new javax.swing.JMenu();
        jMenu4 = new javax.swing.JMenu();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenu5 = new javax.swing.JMenu();

        jMenuItem3.setText("jMenuItem3");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(51, 153, 255));
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(null);

        jMenu1.setText("Master");
        jMenu1.addMenuListener(new javax.swing.event.MenuListener() {
            public void menuCanceled(javax.swing.event.MenuEvent evt) {
            }
            public void menuDeselected(javax.swing.event.MenuEvent evt) {
            }
            public void menuSelected(javax.swing.event.MenuEvent evt) {
                jMenu1MenuSelected(evt);
            }
        });

        MenuKaryawan.setText("Master Karyawan");
        MenuKaryawan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuKaryawanActionPerformed(evt);
            }
        });
        jMenu1.add(MenuKaryawan);

        MenuBidang.setText("Master Bidang");
        MenuBidang.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                MenuBidangActionPerformed(evt);
            }
        });
        jMenu1.add(MenuBidang);

        jMenuBar1.add(jMenu1);

        BtnMenuSuratMasuk.setText("Surat Masuk");
        BtnMenuSuratMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BtnMenuSuratMasukMouseClicked(evt);
            }
        });
        BtnMenuSuratMasuk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnMenuSuratMasukActionPerformed(evt);
            }
        });
        jMenuBar1.add(BtnMenuSuratMasuk);

        BtnMenuSuratKeluar.setText("Surat Keluar");
        jMenuBar1.add(BtnMenuSuratKeluar);

        jMenu4.setText("Laporan");

        jMenuItem2.setText("Laporan Surat Masuk");
        jMenu4.add(jMenuItem2);

        jMenuItem1.setText("Laporan Surat Keluar");
        jMenu4.add(jMenuItem1);

        jMenuBar1.add(jMenu4);

        jMenu5.setText("Tentang");
        jMenu5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jMenu5MouseClicked(evt);
            }
        });
        jMenu5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jMenu5ActionPerformed(evt);
            }
        });
        jMenuBar1.add(jMenu5);

        setJMenuBar(jMenuBar1);

        setBounds(0, 0, 722, 468);
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        this.setExtendedState(this.getExtendedState()|JFrame.MAXIMIZED_BOTH);
    }//GEN-LAST:event_formWindowOpened

    private void jMenu1MenuSelected(javax.swing.event.MenuEvent evt) {//GEN-FIRST:event_jMenu1MenuSelected
        // TODO add your handling code here:
        //new frm_Karyawan().setVisible(true);
    }//GEN-LAST:event_jMenu1MenuSelected

    private void MenuKaryawanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuKaryawanActionPerformed
        // TODO add your handling code here:
        new FrmKaryawan().setVisible(true);
    }//GEN-LAST:event_MenuKaryawanActionPerformed

    private void MenuBidangActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_MenuBidangActionPerformed
        // TODO add your handling code here:
        new MasterBidang().setVisible(true);
    }//GEN-LAST:event_MenuBidangActionPerformed

    private void BtnMenuSuratMasukActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnMenuSuratMasukActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnMenuSuratMasukActionPerformed

    private void jMenu5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jMenu5ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jMenu5ActionPerformed

    private void jMenu5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jMenu5MouseClicked
        // TODO add your handling code here:
        new FrmTentang().setVisible(true);
    }//GEN-LAST:event_jMenu5MouseClicked

    private void BtnMenuSuratMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BtnMenuSuratMasukMouseClicked
        // TODO add your handling code here:
        new FrmSuratMasuk().setVisible(true);
    }//GEN-LAST:event_BtnMenuSuratMasukMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MenuUtama.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                //new MenuUtama().setVisible(true);
                MenuUtama mn = new MenuUtama();
                mn.setExtendedState(JFrame.MAXIMIZED_BOTH);
                mn.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenu BtnMenuSuratKeluar;
    private javax.swing.JMenu BtnMenuSuratMasuk;
    private javax.swing.JMenuItem MenuBidang;
    private javax.swing.JMenuItem MenuKaryawan;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu4;
    private javax.swing.JMenu jMenu5;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    // End of variables declaration//GEN-END:variables
}
